platform :ios, '11.0'

target 'Weather App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weather App
  pod 'Alamofire', '~> 4.8.1'
  pod 'SwiftyJSON', '~> 4.0'

  target 'Weather AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
